#!/usr/bin/env python3
"""为 DND 论文复现审查生成紧凑、确定性的仓库证据索引。"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


SKIP_DIRS = {
    ".git", ".hg", ".svn", ".idea", ".vscode", "__pycache__", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", ".tox", ".venv", "venv", "env", "node_modules",
    "dist", "build", "target", "site-packages",
}
TEXT_SUFFIXES = {
    ".py", ".ipynb", ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg",
    ".md", ".txt", ".sh", ".csv", ".tsv", ".r", ".jl", ".cpp", ".cc",
    ".c", ".h", ".hpp",
}
PATTERNS = {
    "图生成": r"erdos|erd[oő]s|stochastic.?block|\bsbm\b|static.?power|power.?law|igraph",
    "标签": r"exhaust|combination|optimal.?set|minimum.?set|label|ground.?truth",
    "连通性": r"strongly.?connected|strong_components|connected_components|\blscc\b|weakly",
    "模型": r"graph.?attention|\bgat\b|gatconv|multi.?head|attention|sigmoid|\belu\b|residual",
    "特征": r"in.?degree|out.?degree|betweenness|pagerank|k.?core|centrality",
    "训练": r"learning.?rate|optimizer|epochs?|loss|backward|checkpoint|seed",
    "评估": r"area.?under|\bauc\b|dismant|remove.?node|corehd|r.?id|r.?od|baseline|ablation",
    "维度与损失": r"in_channels|out_channels|hidden|shape|heads?|concat|residual|bce|cross.?entropy|mse|criterion|sigmoid|logits",
    "结果产物": r"results?|metrics?|figure|plot|csv|checkpoint|state_dict|runtime|elapsed|mean|std",
    "理解与说明": r"limitation|discussion|because|reason|we found|we choose|trade.?off|ambigu|failure|future",
    "AI风险迹象": r"todo|placeholder|dummy|mock|fake|generated by|as an ai|pass\s*(#.*)?$|except\s*:\s*$",
    "测试": r"pytest|unittest|test_|assert",
}


def is_probably_text(path: Path) -> bool:
    return path.suffix.lower() in TEXT_SUFFIXES or path.name.lower() in {
        "dockerfile", "makefile", "requirements.txt", "environment.yml", "pyproject.toml"
    }


def scan(root: Path, max_bytes: int) -> dict:
    files: list[dict] = []
    hits = {key: [] for key in PATTERNS}
    compiled = {key: re.compile(value, re.I) for key, value in PATTERNS.items()}

    for current, dirs, names in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and not d.startswith(".cache"))
        for name in sorted(names):
            path = Path(current) / name
            rel = path.relative_to(root).as_posix()
            try:
                size = path.stat().st_size
            except OSError:
                continue
            entry = {"path": rel, "size": size, "suffix": path.suffix.lower()}
            files.append(entry)
            if not is_probably_text(path) or size > max_bytes:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            for lineno, line in enumerate(text.splitlines(), 1):
                compact = line.strip()
                if not compact:
                    continue
                for category, pattern in compiled.items():
                    if pattern.search(compact) and len(hits[category]) < 200:
                        hits[category].append({
                            "file": rel,
                            "line": lineno,
                            "text": compact[:240],
                        })

    return {
        "root": str(root.resolve()),
        "file_count": len(files),
        "files": files,
        "candidate_evidence": hits,
        "使用限制": [
            "关键词命中只用于导航，不能直接作为符合性结论。",
            f"超过 {max_bytes} 字节的文本文件未扫描内容。",
            "生成文件、二进制文件和 Notebook 输出需要人工检查。",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo", type=Path, help="需要索引的仓库或代码文件夹")
    parser.add_argument("--output", type=Path, help="JSON 输出路径；省略时输出到终端")
    parser.add_argument("--max-bytes", type=int, default=1_000_000)
    args = parser.parse_args()
    root = args.repo.expanduser().resolve()
    if not root.is_dir():
        parser.error(f"路径不是文件夹：{root}")
    result = scan(root, args.max_bytes)
    payload = json.dumps(result, ensure_ascii=False, indent=2) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(payload, encoding="utf-8")
    else:
        print(payload, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
